app:
  title: "Available tests"
  description: "Available tests "
  version: "0.0.1-SNAPSHOT"
  tos:
    url: "http://www.t3t0.co.uk/licence.html"
  licence:
    type: "Subscription"
    url: "No url"
  contact: "Nobody yet"
  supportUrl: "No url yet"
  email: "Like you will get a reply"
  mode: "debug"
features:
    file: D:\GitHub\teto-repo\TETO_HOME\tests\features.yaml
drools:
  directory: D:/GitHub/teto2/teto2/TETO_HOME/rules/html
environment: default
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6112/eureka
server:
  port: 6117
spring:
    datasource:
        password: Pr!cele22
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/t3t0
        username: root
    jpa:
        hibernate:
            ddl-auto: update
