app:
  title: "Vaadin"
  description: "Vaadin UI"
  version: "0.0.1-SNAPSHOT"
  tos:
    url: "http://www.t3t0.co.uk/licence.html"
  licence:
    type: "Subscription"
    url: "No url"
  contact: "Nobody yet"
  supportUrl: "No url yet"
  email: "Like you will get a reply"
drools:
  directory: D:/GitHub/teto-repo/TETO_HOME/rules/html
environment: default
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6112/eureka
server:
  port: 6118
spring:
    datasource:
        password: Pr!cele22
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/t3t0
        username: root
    jpa:
        hibernate:
            ddl-auto: update
